DROP TABLE IF EXISTS ODONTOLOGOS;
 CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(100) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL );


-- para test --
INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('1122334', 'Bruno', 'Figini'), ('443232', 'Joel', 'Acosta');